version: '3'
services:
  web:
    image: kiwitcms/kiwi:latest
    ports:
      - "8090:8080"  # Kiwi écoute HTTP sur 8080 à l'intérieur
    environment:
      - KIWI_DB_HOST=db
      - KIWI_DB_PORT=5432
      - KIWI_DB_NAME=kiwi
      - KIWI_DB_USER=kiwi
      - KIWI_DB_PASSWORD=kiwi
      - KIWI_TC_SERVER_HTTP=1

    depends_on:
      - db
    volumes:
      - uploads:/Kiwi/uploads

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=kiwi
      - POSTGRES_USER=kiwi
      - POSTGRES_PASSWORD=kiwi
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  uploads:
  db_data:
